modLoader = "javafml"
loaderVersion = "*" # Instead define minecraft versions at the bottom
issueTrackerURL = "${issues}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = $mod_authors
displayURL = "${homepage}"
description = "${description}"
logoFile = "icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${compatible_forgemc_versions}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "balm"
type = "required"
versionRange = "[${balm_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"